config/routes.rb
Rails.application.routes.draw do
  root to: "pages#index"
  
  resources :guestbook_entries
  resources :likes

end

app/models/guestbook_entry.rb
class GuestbookEntry < ActiveRecord::Base
  validates :body,
    format: { message: "contains a bad word", without: /silly/i },
    length: { maximum: 255 },
    presence: true

  has_one :like, dependent: :destroy

  scope :limited, -> { limit(5) }
  scope :most_recent_first, -> { order("created_at DESC") }
  scope :most_recent_limited, -> { limited.most_recent_first.recent }
  scope :recent, -> { where(["created_at >= ?", 30.days.ago]) }

  # after_save :create_like


  def create_like
    Like.create(guestbook_entry_id: self.id)
  end

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :guestbook_entry
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/guestbook_entries_controller.rb
class GuestbookEntriesController < ApplicationController

  def create
    @guestbook_entry = GuestbookEntry.new(guestbook_entry_params)

    if @guestbook_entry.save
      redirect_to root_path, notice: "Thank you for your entry."
    else
      @guestbook_entries = GuestbookEntry.most_recent_limited
      render "pages/welcome"
    end
  end

  def update
    guestbook_entry = GuestbookEntry.find(params[:id])
    @like = guestbook_entry.like.increment(:num_likes)

    if @like.save
      flash[:notice] = 'New like saved!'
      redirect_to root_path
    else
      flash[:notice] = 'Sorry, your like could not be saved.'
      render :'pages/welcome'
    end
  end

  private

  def guestbook_entry_params
    params.require(:guestbook_entry).permit(:body)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @like = Like.new(like_params)
    @guestbook_entry = GuestbookEntry.find(params[:])

    if @like.save
      flash[:notice] = 'New like saved!'
      redirect_to root_path
    else
      flash[:notice] = 'Sorry, your like could not be saved.'
      render :'pages/welcome'
    end
  end

  private

  def like_params
    params.require(:like).permit(:num_likes)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @guestbook_entries = GuestbookEntry.most_recent_limited
    @guestbook_entry = GuestbookEntry.new
    render "welcome"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Guestbook</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
    <style>
    html { margin: 2% 5% 2% 5% }
    </style>
  </head>
  <body>
    <p>
      <%= flash[:notice] %>
    </p>
    <% if flash[:notice] %>
      <hr>
    <% end %>

    <%= yield %>

  </body>
</html>

app/views/pages/welcome.html.erb
<h1>Welcome to My Guestbook</h1>
<br>

<div id="guestbook-entries">
  <h2>Guestbook Entries:</h2>
  <ul>
    <% if @guestbook_entries.any? %>
      <% @guestbook_entries.each do |guestbook_entry| %>
        <li>
          <%= guestbook_entry.created_at.strftime("%b %d %Y:") %>
          <%= guestbook_entry.body %>
          <p class="like-count">
            <%= button_to "Like", guestbook_entry_path(guestbook_entry), method: :patch, action: :update %>
            <%= guestbook_entry.like ? "(#{guestbook_entry.like.num_likes} likes)" : '(0 likes)' %>
          </p>
        </li>
      <% end %>
    <% end %>
  </ul>
</div>

<div id="error-explanation">
  <p>
    <% if @guestbook_entry.errors.any? %>
      <%= pluralize(@guestbook_entry.errors.count, "error") %>
      prohibited this entry from being saved:
    <% end %>
  </p>

  <ul>
    <% @guestbook_entry.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
</div>

<br>
<hr>
<br>

<%= form_for @guestbook_entry do |f| %>
  <h2><%= f.label :body, "Guestbook Entry:" %></h2>
  <%= f.text_area :body, cols: 60, rows: 8 %><br>
  <%= f.submit "Submit" %>
<% end %>